In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Welcome to ShopSphere!")
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

ModuleNotFoundError: No module named 'matplotlib'

In [1]:
import sys

print(sys.executable)

c:\Users\hp\Desktop\ShopSphere\.venv\Scripts\python.exe

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Welcome to ShopSphere!")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Environment:", sys.executable)

Welcome to ShopSphere!
Pandas: 3.0.5
NumPy: 2.5.2
Environment: c:\Users\hp\Desktop\ShopSphere\.venv\Scripts\python.exe

In [3]:
import pandas as pd

customers = pd.read_csv("../data/raw/customers.csv")

customers.head()

,customer_id,first_name,last_name,gender,date_of_birth,city,state,pincode,signup_date,customer_type
0,C00001,Daksh,Bakshi,Male,1979-05-17,Delhi,Delhi,321819,2024-11-23,Customer
1,C00002,Anamika,Balan,Female,1967-01-13,Ahmedabad,Gujarat,389083,2025-07-10,Customer
2,C00003,Shaurya,Kannan,Male,1991-03-25,Chennai,Tamil Nadu,26542,2024-06-16,Customer
3,C00004,Om,Chaudry,Male,1966-12-21,Visakhapatnam,Andhra Pradesh,155940,2025-07-20,Customer
4,C00005,Victor,Yadav,Male,1969-02-25,Faridabad,Haryana,184959,2024-05-29,Customer

In [4]:
customers.shape

(20000, 10)

In [5]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    20000 non-null  str
 1   first_name     20000 non-null  str
 2   last_name      20000 non-null  str
 3   gender         20000 non-null  str
 4   date_of_birth  20000 non-null  str
 5   city           20000 non-null  str
 6   state          20000 non-null  str
 7   pincode        20000 non-null  int64
 8   signup_date    20000 non-null  str
 9   customer_type  20000 non-null  str
dtypes: int64(1), str(9)
memory usage: 1.5 MB

In [6]:
customers.isna().sum()

customer_id      0
first_name       0
last_name        0
gender           0
date_of_birth    0
city             0
state            0
pincode          0
signup_date      0
customer_type    0
dtype: int64

In [7]:
orders = pd.read_csv(
    "../data/raw/orders.csv",
    parse_dates=["order_date"]
)

orders.head()

  order_id customer_id order_date order_status sales_channel
0  O000001      C03649 2024-10-27      Shipped       Website
1  O000002      C04573 2025-04-28    Delivered   Marketplace
2  O000003      C02849 2025-11-16    Delivered       Website
3  O000004      C07165 2025-03-28    Delivered       Website
4  O000005      C06516 2025-12-30    Delivered       Website

In [8]:
orders.shape

(100000, 5)

In [9]:
orders["order_id"].nunique()

100000

In [10]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [11]:
orders["customer_id"].isin(
    customers["customer_id"]
).all()

np.True_

In [12]:
customer_signup = customers[
    ["customer_id", "signup_date"]
]

order_check = orders.merge(
    customer_signup,
    on="customer_id",
    how="left"
)

(
    order_check["order_date"]
    >= order_check["signup_date"]
).all()

np.True_

In [13]:
orders.isna().sum()

order_id         0
customer_id      0
order_date       0
order_status     0
sales_channel    0
dtype: int64

In [14]:
orders["sales_channel"].value_counts()

sales_channel
Website        44992
Mobile App     39918
Marketplace    15090
Name: count, dtype: int64

In [15]:
orders["order_date"].min()

Timestamp('2024-01-01 00:00:00')

In [16]:
orders["order_date"].max()

Timestamp('2025-12-31 00:00:00')

In [17]:
order_items = pd.read_csv(
    "../data/raw/order_items.csv"
)

order_items.head(10)

  order_id product_id  quantity  unit_price  discount_pct
0  O000001     P00026         2      5800.0             0
1  O000002     P00755         2      4150.0            20
2  O000002     P00105         1      7650.0             5
3  O000003     P00096         1      9340.0            10
4  O000004     P00575         1      7030.0            10
5  O000005     P00430         2      7320.0             0
6  O000005     P00226         2      2920.0            10
7  O000005     P00460         1      4850.0             0
8  O000005     P00604         3      4010.0             5
9  O000005     P00285         1      1280.0             0

In [18]:
order_items.shape

(300323, 5)

In [19]:
order_items["order_id"].nunique()

100000

In [20]:
order_items["order_id"].isin(
    orders["order_id"]
).all()

np.True_

In [23]:
products = pd.read_csv(
    "../data/raw/products.csv"
)

products.head()

,product_id,product_name,category,subcategory,brand,selling_price,cost_price,stock_quantity,rating,launch_date
0,P00001,KnowledgeHouse Ultra Fiction,Books,Fiction,KnowledgeHouse,1100,790,377,3.2,2023-06-22
1,P00002,KnowledgeHouse Modern Self Help,Books,Self Help,KnowledgeHouse,1830,1440,47,3.5,2023-02-08
2,P00003,FitCore Everyday Sportswear,Sports & Fitness,Sportswear,FitCore,6760,3710,359,4.0,2024-03-03
3,P00004,TrendRoot Ultra Trousers,Fashion,Trousers,TrendRoot,6930,3440,388,4.4,2024-01-16
4,P00005,ReadMore Ultra Business,Books,Business,ReadMore,740,540,390,3.7,2023-12-13

In [24]:
order_items["quantity"].describe()

count    300323.000000
mean          1.511013
std           0.793775
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max           4.000000
Name: quantity, dtype: float64

In [25]:
order_items["discount_pct"].value_counts().sort_index()

discount_pct
0     90240
5     60186
10    74824
15    36167
20    23845
25    15061
Name: count, dtype: int64

In [26]:
order_items["gross_amount"] = (
    order_items["quantity"]
    * order_items["unit_price"]
)

order_items["discount_amount"] = (
    order_items["gross_amount"]
    * order_items["discount_pct"]
    / 100
)

order_items["net_revenue"] = (
    order_items["gross_amount"]
    - order_items["discount_amount"]
)

In [27]:
order_items[
    [
        "order_id",
        "product_id",
        "quantity",
        "unit_price",
        "discount_pct",
        "gross_amount",
        "discount_amount",
        "net_revenue"
    ]
].head(10)

,order_id,product_id,quantity,unit_price,discount_pct,gross_amount,discount_amount,net_revenue
0,O000001,P00026,2,5800.0,0,11600.0,0.0,11600.0
1,O000002,P00755,2,4150.0,20,8300.0,1660.0,6640.0
2,O000002,P00105,1,7650.0,5,7650.0,382.5,7267.5
3,O000003,P00096,1,9340.0,10,9340.0,934.0,8406.0
4,O000004,P00575,1,7030.0,10,7030.0,703.0,6327.0
5,O000005,P00430,2,7320.0,0,14640.0,0.0,14640.0
6,O000005,P00226,2,2920.0,10,5840.0,584.0,5256.0
7,O000005,P00460,1,4850.0,0,4850.0,0.0,4850.0
8,O000005,P00604,3,4010.0,5,12030.0,601.5,11428.5
9,O000005,P00285,1,1280.0,0,1280.0,0.0,1280.0

In [28]:
orders.columns.tolist()

['order_id', 'customer_id', 'order_date', 'order_status', 'sales_channel']

In [29]:
orders.head()

  order_id customer_id order_date order_status sales_channel
0  O000001      C03649 2024-10-27      Shipped       Website
1  O000002      C04573 2025-04-28    Delivered   Marketplace
2  O000003      C02849 2025-11-16    Delivered       Website
3  O000004      C07165 2025-03-28    Delivered       Website
4  O000005      C06516 2025-12-30    Delivered       Website

In [30]:
orders.dtypes

order_id                    str
customer_id                 str
order_date       datetime64[us]
order_status                str
sales_channel               str
dtype: object

In [31]:
orders.shape

(100000, 5)

## 6. Payment Data Validation

Before cleaning the payment data, we will:
- Inspect its structure
- Check data types
- Check missing values
- Check duplicate payments
- Check payment methods and statuses
- Check whether every payment belongs to a valid order
- Check payment amount distribution

In [32]:
payments = pd.read_csv("../data/raw/payments.csv")

print("Payments dataset loaded successfully!")
print("Shape:", payments.shape)

payments.head()

Payments dataset loaded successfully!
Shape: (100000, 6)

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
0,PAY0000001,O000001,2024-10-29,Net Banking,Successful,11600.0
1,PAY0000002,O000002,2025-05-01,Credit Card,Successful,13907.5
2,PAY0000003,O000003,2025-11-16,UPI,Successful,8406.0
3,PAY0000004,O000004,2025-03-30,Debit Card,Successful,6327.0
4,PAY0000005,O000005,2026-01-01,Credit Card,Successful,37454.5

In [33]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   payment_id      100000 non-null  str
 1   order_id        100000 non-null  str
 2   payment_date    100000 non-null  str
 3   payment_method  100000 non-null  str
 4   payment_status  100000 non-null  str
 5   payment_amount  100000 non-null  float64
dtypes: float64(1), str(5)
memory usage: 4.6 MB

In [34]:
payments.describe(include="all")

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
count,100000,100000,100000,100000,100000,100000.000000
unique,100000,100000,729,6,3,NaN
top,PAY0000001,O000001,2025-12-30,UPI,Successful,NaN
freq,1,1,800,37858,87329,NaN
mean,NaN,NaN,NaN,NaN,NaN,48421.435985
std,NaN,NaN,NaN,NaN,NaN,54352.929643
min,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,NaN,10727.000000
50%,NaN,NaN,NaN,NaN,NaN,30256.000000
75%,NaN,NaN,NaN,NaN,NaN,67095.250000
max,NaN,NaN,NaN,NaN,NaN,670559.000000

In [35]:
print("Missing values:")
print(payments.isnull().sum())

Missing values:
payment_id        0
order_id          0
payment_date      0
payment_method    0
payment_status    0
payment_amount    0
dtype: int64

In [36]:
print("Duplicate rows:", payments.duplicated().sum())

Duplicate rows: 0

In [37]:
print("Payment methods:")
print(payments["payment_method"].value_counts())

print("\nPayment statuses:")
print(payments["payment_status"].value_counts())

Payment methods:
payment_method
UPI                 37858
Credit Card         21990
Debit Card          16005
Net Banking         10141
Cash on Delivery     7905
Wallet               6101
Name: count, dtype: int64

Payment statuses:
payment_status
Successful    87329
Refunded       8458
Failed         4213
Name: count, dtype: int64

In [38]:
invalid_payments = payments[
    ~payments["order_id"].isin(orders["order_id"])
]

print("Invalid payment records:", len(invalid_payments))

Invalid payment records: 0

In [39]:
print("Minimum payment:", payments["payment_amount"].min())
print("Maximum payment:", payments["payment_amount"].max())
print("Average payment:", payments["payment_amount"].mean())
print("Total payments:", payments["payment_amount"].sum())

Minimum payment: 0.0
Maximum payment: 670559.0
Average payment: 48421.435985
Total payments: 4842143598.5

## 6.1 Investigating Zero-Value Payments

A payment amount of zero may indicate a failed, cancelled, refunded,
or otherwise invalid transaction.

We will investigate the associated payment status before deciding
whether these records should be removed or retained.

In [40]:
zero_payments = payments[payments["payment_amount"] == 0]

print("Number of zero-value payments:", len(zero_payments))

zero_payments.head(10)

Number of zero-value payments: 4213

,payment_id,order_id,payment_date,payment_method,payment_status,payment_amount
7,PAY0000008,O000008,2025-07-07,Debit Card,Failed,0.0
17,PAY0000018,O000018,2025-07-01,Net Banking,Failed,0.0
42,PAY0000043,O000043,2025-01-31,UPI,Failed,0.0
59,PAY0000060,O000060,2025-09-09,Credit Card,Failed,0.0
62,PAY0000063,O000063,2025-01-14,Debit Card,Failed,0.0
75,PAY0000076,O000076,2025-05-14,Credit Card,Failed,0.0
91,PAY0000092,O000092,2024-11-16,Debit Card,Failed,0.0
94,PAY0000095,O000095,2024-11-04,UPI,Failed,0.0
125,PAY0000126,O000126,2025-11-07,Credit Card,Failed,0.0
132,PAY0000133,O000133,2024-10-03,Debit Card,Failed,0.0

In [41]:
zero_payments["payment_status"].value_counts()

payment_status
Failed    4213
Name: count, dtype: int64

In [42]:
zero_payments[["payment_status", "payment_method"]].value_counts()

payment_status  payment_method
Failed          UPI                 1615
                Credit Card          969
                Debit Card           653
                Net Banking          407
                Cash on Delivery     332
                Wallet               237
Name: count, dtype: int64

In [43]:
payments.groupby("payment_status")["payment_amount"].agg(
    ["count", "min", "max", "mean", "sum"]
)

                count    min       max          mean           sum
payment_status
Failed           4213    0.0       0.0      0.000000  0.000000e+00
Refunded         8458  135.0  456210.0  49673.730728  4.201404e+08
Successful      87329   82.5  670559.0  50636.136724  4.422003e+09

## 6.2 Payment and Order ID Validation

Payment IDs and Order IDs act as identifiers and relationships
between our datasets.

We will check:
- Duplicate payment IDs
- Missing payment IDs
- Missing order IDs
- Whether every payment belongs to a valid order
- Whether one order has multiple payment records

In [44]:
print("Duplicate payment IDs:", payments["payment_id"].duplicated().sum())

Duplicate payment IDs: 0

In [45]:
print("Missing payment IDs:", payments["payment_id"].isnull().sum())
print("Missing order IDs:", payments["order_id"].isnull().sum())

Missing payment IDs: 0
Missing order IDs: 0

In [46]:
invalid_order_payments = payments[
    ~payments["order_id"].isin(orders["order_id"])
]

print("Payments with invalid order IDs:", len(invalid_order_payments))

Payments with invalid order IDs: 0

In [47]:
payments_per_order = payments.groupby("order_id").size()

print("Orders with multiple payment records:",
      (payments_per_order > 1).sum())

print("\nMaximum payments for a single order:",
      payments_per_order.max())

Orders with multiple payment records: 0

Maximum payments for a single order: 1

# 7. Overall Data Quality Assessment

Before beginning data cleaning, we will perform a consolidated
quality assessment across all ShopSphere datasets.

The assessment will examine:
- Dataset size
- Missing values
- Duplicate records
- Unique identifiers
- Referential integrity
- Numerical ranges
- Categorical values
- Potential business-rule violations

In [48]:
datasets = {
    "Customers": customers,
    "Products": products,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments
}

overview = []

for name, df in datasets.items():
    overview.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

quality_overview = pd.DataFrame(overview)

quality_overview

       Dataset    Rows  Columns  Missing Values  Duplicate Rows
0    Customers   20000       10               0               0
1     Products    1000       10               0               0
2       Orders  100000        5               0               0
3  Order Items  300323        8               0               0
4     Payments  100000        6               0               0

In [49]:
for name, df in datasets.items():
    print(f"\n{'='*50}")
    print(name)
    print(f"{'='*50}")
    
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    
    if len(missing) == 0:
        print("No missing values found.")
    else:
        print(missing)

==================================================
Customers
==================================================
No missing values found.

==================================================
Products
==================================================
No missing values found.

==================================================
Orders
==================================================
No missing values found.

==================================================
Order Items
==================================================
No missing values found.

==================================================
Payments
==================================================
No missing values found.

In [50]:
for name, df in datasets.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

Customers: 0 duplicate rows
Products: 0 duplicate rows
Orders: 0 duplicate rows
Order Items: 0 duplicate rows
Payments: 0 duplicate rows

In [51]:
id_columns = {
    "Customers": "customer_id",
    "Products": "product_id",
    "Orders": "order_id",
    "Order Items": "order_item_id",
    "Payments": "payment_id"
}

for name, id_col in id_columns.items():
    df = datasets[name]
    
    print(
        f"{name} | "
        f"Rows: {len(df)} | "
        f"Unique {id_col}: {df[id_col].nunique()} | "
        f"Missing: {df[id_col].isnull().sum()}"
    )

Customers | Rows: 20000 | Unique customer_id: 20000 | Missing: 0
Products | Rows: 1000 | Unique product_id: 1000 | Missing: 0
Orders | Rows: 100000 | Unique order_id: 100000 | Missing: 0

KeyError: 'order_item_id'

In [52]:
print(
    "Orders with invalid customer IDs:",
    (~orders["customer_id"].isin(customers["customer_id"])).sum()
)

print(
    "Order items with invalid order IDs:",
    (~order_items["order_id"].isin(orders["order_id"])).sum()
)

print(
    "Order items with invalid product IDs:",
    (~order_items["product_id"].isin(products["product_id"])).sum()
)

print(
    "Payments with invalid order IDs:",
    (~payments["order_id"].isin(orders["order_id"])).sum()
)

Orders with invalid customer IDs: 0
Order items with invalid order IDs: 0
Order items with invalid product IDs: 0
Payments with invalid order IDs: 0

In [53]:
print("=" * 60)
print("SHOPSPHERE DATA QUALITY SUMMARY")
print("=" * 60)

for name, df in datasets.items():
    print(f"\n{name}")
    print(f"Rows              : {len(df):,}")
    print(f"Columns           : {df.shape[1]}")
    print(f"Missing values    : {df.isnull().sum().sum():,}")
    print(f"Duplicate rows    : {df.duplicated().sum():,}")

============================================================
SHOPSPHERE DATA QUALITY SUMMARY
============================================================

Customers
Rows              : 20,000
Columns           : 10
Missing values    : 0
Duplicate rows    : 0

Products
Rows              : 1,000
Columns           : 10
Missing values    : 0
Duplicate rows    : 0

Orders
Rows              : 100,000
Columns           : 5
Missing values    : 0
Duplicate rows    : 0

Order Items
Rows              : 300,323
Columns           : 8
Missing values    : 0
Duplicate rows    : 0

Payments
Rows              : 100,000
Columns           : 6
Missing values    : 0
Duplicate rows    : 0